version: '3.8'

services:

  sdk:
    image: golang:1.20.5-alpine3.18
    depends_on:
      - db
    volumes:
      - .:/opt/app
    ports:
      - "8088:8080"
    working_dir: /opt/app
    command: go run src/main.go

  db:
    image: postgres:14.1-alpine
    container_name: demo-db
    hostname: demo-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "6432:5432"
    volumes:
      - ./.output/:/opt/db/
      

  # bash:
  #   image: bash:5.1
  #   volumes:
  #     - .:/opt/app
  #     - ./.output/sqls:/opt/scripts
  #   working_dir: /opt/app