version: '3.8'

services:

  sdk:
    build:
      context: . # Use an image built from the specified dockerfile in the current directory.
      dockerfile: Dockerfile
    image: go-test/first-app
    depends_on:
      - db
    volumes:
      - .:/app/opt
    ports:
      - "8088:8080"

  db:
    image: postgres:14.1-alpine
    container_name: demo-db
    hostname: demo-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "6432:5432"
    volumes:
      - ./.output/:/app/opt/db/
      

  # bash:
  #   image: bash:5.1
  #   volumes:
  #     - .:/opt/app
  #     - ./.output/sqls:/opt/scripts
  #   working_dir: /opt/app