name: Migration
on: 
  workflow_dispatch:

env:
  DB_NAME: DemoDb
  INSTANCE_NAME: pg-instance
jobs:
  migration:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
      - name: Create-db
        run: 
          gcloud sql databases create ${DB_NAME} --instance=${INSTANCE_NAME}
      - name: Migrate-db
        run: 
          make migrate-db
